### ISSUE TITLE
does virtual1403 support connections from multiple MVS systems

### ISSUE THREAD

**Issue by dliloch** [racingmars/virtual1403#13]
I would like to put the virtual1403 on a dedicated linux platform and have various MVS systems connect to it. I would have the pdf files stored on the platform. When I tried to do this with just one mvs system I got the following error message:

2024/01/16 10:34:03 INFO:  [default] Re-trying Hercules connection in 10 seconds...
2024/01/16 10:34:13 INFO:  [default] Connecting to Hercules on 192.168.0.165:1403...
2024/01/16 10:34:13 ERROR: [default] Couldn't connect: dial tcp 192.168.0.165:1403: connect: connection refused

my config.yaml has
hercules_address: "192.168.0.165:1403"
mode is local since I am not trying to connect to the server and email me the pdf.

Would this be a new feature or am I doing something wrong? I reviewed the documentation but could not find an answer so I am posting here.. 

Thanks

**Comment by racingmars** [comment]
Hi @dliloch,

Yes, that should work. What does your 1403 device definition look like in your hercules configuration file? It's possible that the socket device is only listening on localhost, which could be why you can't connect from a remote machine. Try something like `00E 0.0.0.0:1403 sockdev` to force it to listen on all IPv4 interfaces. Also ensure you don't have a firewall set up on your Hercules host that may be blocking traffic on the port you've configured (1403).

**Comment by dliloch** [comment]
Matt,
First thanks for getting back to me so quickly!
I really like your virtual pdf printer..

The 0.0.0.0:1403 notation worked great! I can use that in all my MVS instances.
Now however when I try to add another hercules_address line with another ip address I get:
FATAL: unable to read config ‘config.yaml’:yaml: unmarshal errors: line 4 mapping key hercules_address already defined at line 3

I then changed the lines to
hercules_address:     “192.168.0.156:1403”
hercules_address2:   “192.168.0.143:1403”
No errors but the second address did not contact the 143 system…the printer on that system just active and when I interrupt it or try and purge it it will not drain..
So how can I add another system?
Thanks,
Don Isenstadt

**Comment by racingmars** [comment]
@dliloch Hi Don,

Glad the connection is working for you now.

To connect to multiple inputs (e.g. multiple different Hercules instances), you can take a look toward the bottom of the sample config file in the "ADVANCED CONFIGURATION - MULTIPLE INPUTS/OUTPUTS" section. There you can see how you can create multiple different inputs, each connecting to a different host. In the YAML syntax, that `-` (hyphen) character before the different `name:` entries is what begins a new block of configuration (`name`, `hercules_address`, `output`). The comment block in that section explains it a little bit more.
