### ISSUE TITLE
After upgrading to Ubuntu 24.04 on a raspberry pi K400 virtual1403 fails to start

### ISSUE THREAD

**Issue by dliloch** [racingmars/virtual1403#14]
Here is the output after I started virtual1403

pi@ubuntuK400:~$ cd Desktop/virtual*
pi@ubuntuK400:~/Desktop/virtual1403-agent$ ./virtual1403
futexwakeup addr=0x604318 returned -38
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1006 pc=0x45800]

runtime stack:
runtime.throw({0x3a6241, 0x2a})
        runtime/panic.go:1047 +0x4c fp=0x143ff4c sp=0x143ff38 pc=0x49ac8
runtime.sigpanic()
        runtime/signal_unix.go:819 +0x218 fp=0x143ff64 sp=0x143ff4c pc=0x62594
runtime.futexwakeup(0x604318, 0x1)
        runtime/os_linux.go:94 +0x84 fp=0x143ff94 sp=0x143ff68 pc=0x45800futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x142e550 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
fatal error: unexpected signal during runtime execution
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
fatal error: unexpected signal during runtime execution
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
fatal error: unexpected signal during runtime execution
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
fatal error: unexpected signal during runtime execution
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
futexwakeup addr=0x617268 returned -38
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
panic during panic
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1006 pc=0x45800]

runtime stack:
runtime.throw({0x3a6241, 0x2a})
        runtime/panic.go:1047 +0x4c fp=0x143f6f4 sp=0x143f6e0 pc=0x49ac8
runtime.sigpanic()
        runtime/signal_unix.go:819 +0x218 fp=0x143f70c sp=0x143f6f4 pc=0x62594
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:94 +0x84 fp=0x143f73c sp=0x143f710 pc=0x45800
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143f754 sp=0x143f73c pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143f75c sp=0x143f754 pc=0x4bad0
runtime.futexwakeup.func1()
        runtime/os_linux.go:91 +0x74 fp=0x143f770 sp=0x143f75c pc=0x45884
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:90 +0x7c fp=0x143f79c sp=0x143f770 pc=0x457f8
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143f7b4 sp=0x143f79c pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143f7bc sp=0x143f7b4 pc=0x4bad0
runtime.throw.func1()
        runtime/panic.go:1044 +0x54 fp=0x143f7d0 sp=0x143f7bc pc=0x49b28
runtime.throw({0x3a6241, 0x2a})
        runtime/panic.go:1043 +0x40 fp=0x143f7e4 sp=0x143f7d0 pc=0x49abc
runtime.sigpanic()
        runtime/signal_unix.go:819 +0x218 fp=0x143f7fc sp=0x143f7e4 pc=0x62594
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:94 +0x84 fp=0x143f82c sp=0x143f800 pc=0x45800
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143f844 sp=0x143f82c pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143f84c sp=0x143f844 pc=0x4bad0
runtime.throw.func1()
        runtime/panic.go:1044 +0x54 fp=0x143f860 sp=0x143f84c pc=0x49b28
runtime.throw({0x3a6241, 0x2a})
        runtime/panic.go:1043 +0x40 fp=0x143f874 sp=0x143f860 pc=0x49abc
runtime.sigpanic()
        runtime/signal_unix.go:819 +0x218 fp=0x143f88c sp=0x143f874 pc=0x62594
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:94 +0x84 fp=0x143f8bc sp=0x143f890 pc=0x45800
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143f8d4 sp=0x143f8bc pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143f8dc sp=0x143f8d4 pc=0x4bad0
runtime.futexwakeup.func1()
        runtime/os_linux.go:91 +0x74 fp=0x143f8f0 sp=0x143f8dc pc=0x45884
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:90 +0x7c fp=0x143f91c sp=0x143f8f0 pc=0x457f8
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143f934 sp=0x143f91c pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143f93c sp=0x143f934 pc=0x4bad0
runtime.throw.func1()
        runtime/panic.go:1044 +0x54 fp=0x143f950 sp=0x143f93c pc=0x49b28
runtime.throw({0x3a6241, 0x2a})
        runtime/panic.go:1043 +0x40 fp=0x143f964 sp=0x143f950 pc=0x49abc
runtime.sigpanic()
        runtime/signal_unix.go:819 +0x218 fp=0x143f97c sp=0x143f964 pc=0x62594
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:94 +0x84 fp=0x143f9ac sp=0x143f980 pc=0x45800
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143f9c4 sp=0x143f9ac pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143f9cc sp=0x143f9c4 pc=0x4bad0
runtime.throw.func1()
        runtime/panic.go:1044 +0x54 fp=0x143f9e0 sp=0x143f9cc pc=0x49b28
runtime.throw({0x3a6241, 0x2a})
        runtime/panic.go:1043 +0x40 fp=0x143f9f4 sp=0x143f9e0 pc=0x49abc
runtime.sigpanic()
        runtime/signal_unix.go:819 +0x218 fp=0x143fa0c sp=0x143f9f4 pc=0x62594
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:94 +0x84 fp=0x143fa3c sp=0x143fa10 pc=0x45800
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143fa54 sp=0x143fa3c pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143fa5c sp=0x143fa54 pc=0x4bad0
runtime.futexwakeup.func1()
        runtime/os_linux.go:91 +0x74 fp=0x143fa70 sp=0x143fa5c pc=0x45884
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:90 +0x7c fp=0x143fa9c sp=0x143fa70 pc=0x457f8
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143fab4 sp=0x143fa9c pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143fabc sp=0x143fab4 pc=0x4bad0
runtime.futexwakeup.func1()
        runtime/os_linux.go:91 +0x74 fp=0x143fad0 sp=0x143fabc pc=0x45884
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:90 +0x7c fp=0x143fafc sp=0x143fad0 pc=0x457f8
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143fb14 sp=0x143fafc pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143fb1c sp=0x143fb14 pc=0x4bad0
runtime.futexwakeup.func1()
        runtime/os_linux.go:91 +0x74 fp=0x143fb30 sp=0x143fb1c pc=0x45884
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:90 +0x7c fp=0x143fb5c sp=0x143fb30 pc=0x457f8
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143fb74 sp=0x143fb5c pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143fb7c sp=0x143fb74 pc=0x4bad0
runtime.futexwakeup.func1()
        runtime/os_linux.go:91 +0x74 fp=0x143fb90 sp=0x143fb7c pc=0x45884
runtime.futexwakeup(0x617268, 0x1)
        runtime/os_linux.go:90 +0x7c fp=0x143fbbc sp=0x143fb90 pc=0x457f8
runtime.unlock2(0x617268)
        runtime/lock_futex.go:121 +0x70 fp=0x143fbd4 sp=0x143fbbc pc=0x1a42c
runtime.unlockWithRank(...)
        runtime/lockrank_off.go:32
runtime.unlock(...)
        runtime/lock_futex.go:112
runtime.printunlock()
        runtime/print.go:80 +0x3c fp=0x143fbdc sp=0x143fbd4 pc=0x4bad0
runtime.gentraceback(0x49ac8, 0x143ff38, 0x0, 0x14024b0, 0x0, 0x0, 0x64, 0x0, 0x0, 0x0)
        runtime/traceback.go:455 +0x1630 fp=0x143fdd0 sp=0x143fbdc pc=0x711c4
runtime.traceback1(0x49ac8, 0x143ff38, 0x0, 0x14024b0, 0x0)
        runtime/traceback.go:846 +0x19c fp=0x143feb0 sp=0x143fdd0 pc=0x723bc
runtime.traceback(0x49ac8, 0x143ff38, 0x0, 0x14024b0)
        runtime/traceback.go:793 +0x3c fp=0x143fec8 sp=0x143feb0 pc=0x72188
runtime.dopanic_m(0x14024b0, 0x49ac8, 0x143ff38)
        runtime/panic.go:1266 +0x210 fp=0x143fefc sp=0x143fec8 pc=0x4a3a0
runtime.fatalthrow.func1()
        runtime/panic.go:1125 +0x48 fp=0x143ff1c sp=0x143fefc pc=0x49e0c
runtime.fatalthrow(0x2)
        runtime/panic.go:1122 +0x64 fp=0x143ff38 sp=0x143ff1c pc=0x49dac
runtime.throw({0x3a6241, 0x2a})
        runtime/panic.go:1047 +0x4c fp=0x143ff4c sp=0x143ff38 pc=0x49ac8
runtime.sigpanic()
        runtime/signal_unix.go:819 +0x218 fp=0x143ff64 sp=0x143ff4c pc=0x62594
runtime.futexwakeup(0x604318, 0x1)
        runtime/os_linux.go:94 +0x84 fp=0x143ff94 sp=0x143ff68 pc=0x45800
runtime.notewakeup(0x604318)
        runtime/lock_futex.go:145 +0x68 fp=0x143ffac sp=0x143ff94 pc=0x1a518
runtime.startlockedm(0x14020f0)
        runtime/proc.go:2469 +0x60 fp=0x143ffbc sp=0x143ffac pc=0x51ae0
runtime.schedule()
        runtime/proc.go:3240 +0x70 fp=0x143ffd8 sp=0x143ffbc pc=0x53e58
runtime.mstart1()
        runtime/proc.go:1432 +0xb0 fp=0x143ffe8 sp=0x143ffd8 pc=0x4f84c
runtime.mstart0()
        runtime/proc.go:1382 +0x68 fp=0x143fffc sp=0x143ffe8 pc=0x4f780
runtime.mstart()
        runtime/asm_arm.s:210 +0x8 fp=0x1440000 sp=0x143fffc pc=0x7a9a8

goroutine 1 [runnable, locked to thread]:
runtime.gcenable()
        runtime/mgc.go:175 +0xfc fp=0x142a7c0 sp=0x142a7c0 pc=0x27e58
runtime.main()
        runtime/proc.go:209 +0x160 fp=0x142a7ec sp=0x142a7c0 pc=0x4c898
runtime.goexit()
        runtime/asm_arm.s:831 +0x4 fp=0x142a7ec sp=0x142a7ec pc=0x7c590

goroutine 2 [runnable]:
runtime.forcegchelper()
        runtime/proc.go:293 fp=0x142afec sp=0x142afec pc=0x4cc0c
runtime.goexit()
        runtime/asm_arm.s:831 +0x4 fp=0x142afec sp=0x142afec pc=0x7c590
created by runtime.init.5
        runtime/proc.go:290 +0x1c
futexwakeup addr=0x6172e0 returned -38
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1006 pc=0x45800]
futexwakeup addr=0x617268 returned -38
fatal error: unexpected signal during runtime execution
stack trace unavailable
pi@ubuntuK400:~/Desktop/virtual1403-agent$

**Comment by racingmars** [comment]
Interesting. That's usually an indication that the kernel version is too old to be supported by Go, but that seems unlike with any Ubuntu 24.04 distribution. It's making a system call that doesn't exist in the kernel. I'll have to see if this has popped up as a known problem anywhere...

**Comment by dliloch** [comment]
Thanks for looking at it..if you need anything further from me just let me know.Sent from my iPad Air 2On Jun 30, 2024, at 4:37 AM, Matthew R. Wilson ***@***.***> wrote:﻿
Interesting. That's usually an indication that the kernel version is too old to be supported by Go, but that seems unlike with any Ubuntu 24.04 distribution. It's making a system call that doesn't exist in the kernel. I'll have to see if this has popped up as a known problem anywhere...

**Comment by racingmars** [comment]
Hi @dliloch,

I've added new v0.5.2 builds to Github, https://github.com/racingmars/virtual1403/releases/tag/v0.5.2

This release includes a few new ARM for Linux variants in the pre-built binaries, and is built with the more recent Go compiler version.

Before, the only Linux ARM build was the 32-bit linux-armv7 package. Now there are linux-armv6, linux-arm64v6, linux-armv7, and linux-arm64v7 builds.

Could you please try the various Linux ARM builds and see if one of them works for you on the Pi400 without getting that crash?

**Comment by dliloch** [comment]
Thank you sooo much... I love virtual1403 and the great support you've shown for the product.. I tested it on both my pi5 running raspian bookworm and the k400 rapsperry pi runing ubuntu 24.04.. works great on both.. below is the starting output for the Ubuntu 24.04
pi@ubuntuK400:~/Desktop/virtual1403-agent$ ./virtual1403
       _      _               _   _ _  _    ___ _____
__   _(_)_ __| |_ _   _  __ _| | / | || |  / _ \___ /
\ \ / / | '__| __| | | |/ _` | | | | || |_| | | ||_ \
 \ V /| | |  | |_| |_| | (_| | | | |__   _| |_| |__) |
  \_/ |_|_|   \__|\__,_|\__,_|_| |_|  |_|  \___/____/

virtual1403 <https://github.com/racingmars/virtual1403/>
  copyright 2021-2022 Matthew R. Wilson.

virtual1403 is free software, distributed under the GPL v3
  (or later) license; see COPYING for details.

Version 0.5.2

2024/07/04 04:47:29 INFO:  [default] Using default font
2024/07/04 04:47:29 INFO:  [default1] Using default font
2024/07/04 04:47:29 INFO:  starting input/output pair [default]/[default]
2024/07/04 04:47:29 INFO:  [default] Will create PDFs in directory `pdfs`
2024/07/04 04:47:29 INFO:  [default] Connecting to Hercules on 127.0.0.1:1403...
2024/07/04 04:47:29 INFO:  [default] Connection successful.
2024/07/04 04:47:29 INFO:  starting input/output pair [mvsp4]/[default1]
2024/07/04 04:47:29 INFO:  [mvsp4] Will create PDFs in directory `pdfs`
2024/07/04 04:47:29 INFO:  [mvsp4] Connecting to Hercules on 192.168.0.143:1403...
2024/07/04 04:47:29 ERROR: [mvsp4] Couldn't connect: dial tcp 192.168.0.143:1403: connect: connection refused
2024/07/04 04:47:29 INFO:  [mvsp4] Re-trying Hercules connection in 10 seconds...
2024/07/04 04:47:30 INFO:  starting input/output pair [mvspi5]/[default1]
2024/07/04 04:47:30 INFO:  [mvspi5] Will create PDFs in directory `pdfs`
2024/07/04 04:47:30 INFO:  [mvspi5] Connecting to Hercules on 192.168.0.165:1403...
2024/07/04 04:47:30 INFO:  [mvspi5] Connection successful.
2024/07/04 04:47:39 INFO:  [mvsp4] Connecting to Hercules on 192.168.0.143:1403...
the 143 address was down at the time ...

**Comment by racingmars** [comment]
Great, glad it's working now! Have fun!
