### ISSUE TITLE
Sharable PDF link

### ISSUE THREAD

**Issue by moshix** [racingmars/virtual1403#5]
Hello Matthew

amazing job on the web-viewable PDF! Thanks a lot!

What if the PDF would be a sharable link (unique link each time), so people can share with others without having to send an email, and also, since it expires after n days, alleviates the number of PDFs in the email inbox. 

thanks

Moshxi

**Comment by racingmars** [comment]
PDF endpoint is no longer authenticated, and the PDF links are securely non-guessable so that you can send a link to anyone you want to be able to download a particular PDF (until it is deleted from the database after the PDF cleanup period).
