### ISSUE TITLE
Stand-alone version

### ISSUE THREAD

**Issue by dinosv** [racingmars/virtual1403#8]
Do you think it is possible to implement a stand-alone version to process plain text files? I used **enscript** to print my txt files to PDF, but it didn't allow using Unicode glyphs. Now I use **paps**, but it lacks background line highlighting.

**Comment by racingmars** [comment]
It would be pretty straightforward.

You mention using Unicode glyphs. Are you making arbitrary text files, not just printer output from Hercules? Right now virtual1403 assumes it's from Hercules and translates from the character encoding that Hercules outputs into utf-8 strings internally; if you're just wanting to run files through that are already utf-8 encoded, we would need to add a flag or config value or something to say not to try to do the conversion from the Hercules character encoding.

**Comment by dinosv** [comment]
Yes! I was thinking of arbitrary created utf-8 files.

**Comment by racingmars** [comment]
I've added a "-printfile" flag to the agent which will read a UTF-8/US-ASCII file and print it, instead of connecting to Hercules. Details in the agent readme: https://github.com/racingmars/virtual1403/blob/95b98225f4a2163e8cda3217c8fbc16542f74e8e/agent/README#L22

**Comment by racingmars** [comment]
Release 0.4.0 now out; the pre-build agent binaries now support the -printfile flag: https://github.com/racingmars/virtual1403/releases/tag/v0.4.0
